var Teachers2021 = [
    {"name": "Aiden Ye", "imgurl": "aidenye.jpg"},
    {"name": "Alison Yang", "imgurl": "alisonyang.jpg"},
    {"name": "Amruta Dharmapurikar", "imgurl": "amrutadharmapurikar.jpg"},
    {"name": "Anagha Badriprasad", "imgurl": "anaghabadriprasad.jpg"},
    {"name": "Andrew Peng", "imgurl": "andrewpeng.jpg"},
    {"name": "Andy Xu", "imgurl": "andyxu.jpg"},
    {"name": "Angeline Hu", "imgurl": "angelinehu.jpg"},
    {"name": "Anna Yang", "imgurl": "annayang.jpg"},
    {"name": "Annli Zhu", "imgurl": "annlizhu.jpg"},
    {"name": "Anping Zhu", "imgurl": "anpingzhu.jpg"},
    {"name": "Arnav Swamy", "imgurl": "arnavswamy.jpg"},
    {"name": "Austin Liu", "imgurl": "austinliu.jpg"},
    {"name": "Bohong Su", "imgurl": "bohongsu.jpg"},
    {"name": "Brianna Wang", "imgurl": "briannawang.jpg"},
    {"name": "Bryan Li", "imgurl": "bryanli.jpg"},
    {"name": "Bryan Liu", "imgurl": "bryanliu.jpg"},
    {"name": "Cayden Gu", "imgurl": "caydengu.jpg"},
    {"name": "Charles Li", "imgurl": "charlesli.jpg"},
    {"name": "Chloe Lee", "imgurl": "chloelee.jpg"},
    {"name": "Clark Wang", "imgurl": "clarkwang.jpg"},
    {"name": "Cynthia Jia", "imgurl": "cynthiajia.jpg"},
    {"name": "Dennis Han", "imgurl": "dennishan.jpg"},
    {"name": "Edward Zhang", "imgurl": "edwardzhang.jpg"},
    {"name": "Emma Xia", "imgurl": "emmaxia.jpg"},
    {"name": "Eric Wang", "imgurl": "ericwang.jpg"},
    {"name": "Ethan Lin", "imgurl": "ethanlin.jpg"},
    {"name": "Grace Li", "imgurl": "graceli.jpg"},
    {"name": "Grace Wong", "imgurl": "gracewong.jpg"},
    {"name": "Helen Li", "imgurl": "helenli.jpg"},
    {"name": "Jasmine Hou", "imgurl": "jasminehou.jpg"},
    {"name": "Jasmine Yuan", "imgurl": "jasmineyuan.jpg"},
    {"name": "Jeremy Wang", "imgurl": "jeremywang.jpg"},
    {"name": "Jocelyn Tan", "imgurl": "jocelyntan.jpg"},
    {"name": "Julie Chen", "imgurl": "juliechen.jpg"},
    {"name": "Justin Gu", "imgurl": "justingu.jpg"},
    {"name": "Kaitlyn Wang", "imgurl": "kaitlynwang.jpg"},
    {"name": "Kevin Wang", "imgurl": "kevinwang.jpg"},
    {"name": "Kyleen Liao", "imgurl": "kyleenliao.jpg"},
    {"name": "Leo Yang", "imgurl": "leoyang.jpg"},
    {"name": "Matthew Zhang", "imgurl": "matthewzhang.jpg"},
    {"name": "Max Zhang", "imgurl": "maxzhang.jpg"},
    {"name": "Michael Ma", "imgurl": "michaelma.jpg"},
    {"name": "Michael Song", "imgurl": "michaelsong.jpg"},
    {"name": "Minh Do", "imgurl": "minhdo.jpg"},
    {"name": "Naomi Wong", "imgurl": "naomiwong.jpg"},
    {"name": "Oliver Ye", "imgurl": "oliverye.jpg"},
    {"name": "Rachel Chan", "imgurl": "rachelchan.jpg"},
    {"name": "Royce Ren", "imgurl": "royceren.jpg"},
    {"name": "Samika Swamy", "imgurl": "samikaswamy.jpg"},
    {"name": "Sean Yang", "imgurl": "seanyang.jpg"},
    {"name": "Sharon Zhu", "imgurl": "sharonzhu.jpg"},
    {"name": "Shreyas Rana", "imgurl": "shreyasrana.jpg"},
    {"name": "Sonia Swamy", "imgurl": "soniaswamy.jpg"},
    {"name": "Spencer He", "imgurl": "spencerhe.jpg"},
    {"name": "Sudithi Manthati", "imgurl": "sudithimanthati.jpg"},
    {"name": "Tim Jing", "imgurl": "timjing.jpg"},
    {"name": "Tony Zhou", "imgurl": "tonyzhou.jpg"},
    {"name": "Yitao Li", "imgurl": "yitaoli.jpg"},
];
var Teachers2020 = [
    {"name": "Aiden Ye", "imgurl": "aidenye.jpg"},
    {"name": "Alex Wang", "imgurl": "alexwang.jpg"},
    {"name": "Alex Xu", "imgurl": "alexxu.jpg"},
    {"name": "Alex Zhang", "imgurl": "alexzhang.jpg"},
    {"name": "Allison Chang", "imgurl": "allisonchang.jpg"},
    {"name": "Amruta Dharmapurikar", "imgurl": "amrutadharmapurikar.jpg"},
    {"name": "Anagha Badriprasad", "imgurl": "anaghabadriprasad.jpg"},
    {"name": "Andrew Peng", "imgurl": "andrewpeng.jpg"},
    {"name": "Andy Li", "imgurl": "andyli.jpg"},
    {"name": "Andy Xu", "imgurl": "andyxu.jpg"},
    {"name": "Anna Yang", "imgurl": "annayang.jpg"},
    {"name": "Annli Zhu", "imgurl": "annlizhu.jpg"},
    {"name": "Anouk Yeh", "imgurl": "anoukyeh.jpg"},
    {"name": "Anping Zhu", "imgurl": "anpingzhu.jpg"},
    {"name": "Arthur Ji", "imgurl": "arthurji.jpg"},
    {"name": "Arthur Zhou", "imgurl": "arthurzhou.jpg"},
    {"name": "Audrey Lee", "imgurl": "audreylee.jpg"},
    {"name": "Austin Liu", "imgurl": "austinliu.jpg"},
    {"name": "Bohong Su", "imgurl": "bohongsu.jpg"},
    {"name": "Brianna Wang", "imgurl": "briannawang.jpg"},
    {"name": "Bryan Li", "imgurl": "bryanli.jpg"},
    {"name": "Bryan Liu", "imgurl": "bryanliu.jpg"},
    {"name": "Cayden Gu", "imgurl": "caydengu.jpg"},
    {"name": "Charles Li", "imgurl": "charlesli.jpg"},
    {"name": "Chloe Lee", "imgurl": "chloelee.jpg"},
    {"name": "Chris Lee", "imgurl": "chrislee.jpg"},
    {"name": "Cindy Li", "imgurl": "cindyli.jpg"},
    {"name": "Cindy Xu", "imgurl": "cindyxu.jpg"},
    {"name": "Clark Wang", "imgurl": "clarkwang.jpg"},
    {"name": "Cynthia Jia", "imgurl": "cynthiajia.jpg"},
    {"name": "Dylan Zhang", "imgurl": "dylanzhang.jpg"},
    {"name": "Edward Zhang", "imgurl": "edwardzhang.jpg"},
    {"name": "Eric Wang", "imgurl": "ericwang.jpg"},
    {"name": "Ethan Lin", "imgurl": "ethanlin.jpg"},
    {"name": "Grace Li", "imgurl": "graceli.jpg"},
    {"name": "Grace Wong", "imgurl": "gracewong.jpg"},
    {"name": "Helen Li", "imgurl": "helenli.jpg"},
    {"name": "Jasmine Hou", "imgurl": "jasminehou.jpg"},
    {"name": "Jasmine Yuan", "imgurl": "jasmineyuan.jpg"},
    {"name": "Jeremy Wang", "imgurl": "jeremywang.jpg"},
    {"name": "Jocelyn Tan", "imgurl": "jocelyntan.jpg"},
    {"name": "Justin Gu", "imgurl": "justingu.jpg"},
    {"name": "Kaitlyn Wang", "imgurl": "kaitlynwang.jpg"},
    {"name": "Kevin Shi ", "imgurl": "kevinshi.jpg"},
    {"name": "Kevin Wang", "imgurl": "kevinwang.jpg"},
    {"name": "Leo Weng", "imgurl": "leoweng.jpg"},
    {"name": "Leo Yang", "imgurl": "leoyang.jpg"},
    {"name": "Matthew Zhang", "imgurl": "matthewzhang.jpg"},
    {"name": "Max Zhang", "imgurl": "maxzhang.jpg"},
    {"name": "Michael Ma", "imgurl": "michaelma.jpg"},
    {"name": "Michael Song", "imgurl": "michaelsong.jpg"},
    {"name": "Naomi Wong", "imgurl": "naomiwong.jpg"},
    {"name": "Oliver Ye", "imgurl": "oliverye.jpg"},
    {"name": "Rachel Chan", "imgurl": "rachelchan.jpg"},
    {"name": "Ray Zhou", "imgurl": "rayzhou.jpg"},
    {"name": "Royce Ren", "imgurl": "royceren.jpg"},
    {"name": "Samika Swamy", "imgurl": "samikaswamy.jpg"},
    {"name": "Sean Yang", "imgurl": "seanyang.jpg"},
    {"name": "Sharon Zhu", "imgurl": "sharonzhu.jpg"},
    {"name": "Shreyas Rana", "imgurl": "shreyasrana.jpg"},
    {"name": "Sonia Swamy", "imgurl": "soniaswamy.jpg"},
    {"name": "Spencer He", "imgurl": "spencerhe.jpg"},
    {"name": "Stefan Meier", "imgurl": "stefanmeier.jpg"},
    {"name": "Steven Long", "imgurl": "stevenlong.jpg"},
    {"name": "Sudithi Manthati", "imgurl": "sudithimanthati.jpg"},
    {"name": "Tim Jing", "imgurl": "timjing.jpg"},
    {"name": "Tony Jiang", "imgurl": "tonyjiang.jpg"},
    {"name": "Tony Zhou", "imgurl": "tonyzhou.jpg"},
    {"name": "Trevor Leung", "imgurl": "trevorleung.jpg"},
    {"name": "Victor Shen", "imgurl": "victorshen.jpg"},
    {"name": "Yang Gao", "imgurl": "yanggao.jpg"},
    {"name": "Cynthia Jia", "imgurl": "cynthiajia.jpg"},
    {"name": "Zachary George", "imgurl": "zacharygeorge.jpg"},
];
var Teachers2019 = [
    {"name": "Aiden Ye", "imgurl": "aidenye.jpg"},
    {"name": "Akhil Aggarwal", "imgurl": "akhilaggarwal.jpg"},
    {"name": "Alex Wang", "imgurl": "alexwang.jpg"},
    {"name": "Alex Xu", "imgurl": "alexxu.jpg"},
    {"name": "Alex Zhang", "imgurl": "alexzhang.jpg"},
    {"name": "Allen Chang", "imgurl": "allenchang.jpg"},
    {"name": "Alvin Tian", "imgurl": "alvintian.jpg"},
    {"name": "Andrew Zhao", "imgurl": "andrewzhao.jpg"},
    {"name": "Andy Li", "imgurl": "andyli.jpg"},
    {"name": "Andy Xu", "imgurl": "andyxu.jpg"},
    {"name": "Angelica Wang", "imgurl": "angelicawang.jpg"},
    {"name": "Anna Yang", "imgurl": "annayang.jpg"},
    {"name": "Anouk Yeh", "imgurl": "anoukyeh.jpg"},
    {"name": "Ansh Chaurasia", "imgurl": "anshchaurasia.jpg"},
    {"name": "Arthur Ji", "imgurl": "arthurji.jpg"},
    {"name": "Arthur Zhou", "imgurl": "arthurzhou.jpg"},
    {"name": "Audrey Lee", "imgurl": "audreylee.jpg"},
    {"name": "Austin Liu", "imgurl": "austinliu.jpg"},
    {"name": "Brandon Fu", "imgurl": "brandonfu.jpg"},
    {"name": "Brianna Wang", "imgurl": "briannawang.jpg"},
    {"name": "Charles Li", "imgurl": "charlesli.jpg"},
    {"name": "Chris Lee", "imgurl": "chrislee.jpg"},
    {"name": "Cindy Li", "imgurl": "cindyli.jpg"},
    {"name": "Cindy Xu", "imgurl": "cindyxu.jpg"},
    {"name": "Clark Wang", "imgurl": "clarkwang.jpg"},
    {"name": "Cynthia Jia", "imgurl": "cynthiajia.jpg"},
    {"name": "Darren Zhan", "imgurl": "darrenzhan.jpg"},
    {"name": "Derrick Cai", "imgurl": "derrickcai.jpg"},
    {"name": "Dylan Zhang", "imgurl": "dylanzhang.jpg"},
    {"name": "Emma Lu", "imgurl": "emmalu.jpg"},
    {"name": "Eric Yang", "imgurl": "ericyang.jpg"},
    {"name": "Ethan Lin", "imgurl": "ethanlin.jpg"},
    {"name": "Helen Li", "imgurl": "helenli.jpg"},
    {"name": "Henry Huang", "imgurl": "henryhuang.jpg"},
    {"name": "Isaac Li", "imgurl": "isaacli.jpg"},
    {"name": "Jerry Ying", "imgurl": "jerryying.jpg"},
    // {"name": "Joshua Yin", "imgurl": "joshuayin.jpg"},
    {"name": "Joshua Zhu", "imgurl": "joshuazhu.jpg"},
    {"name": "Julia Zhao", "imgurl": "juliazhao.jpg"},
    {"name": "Leo Yang", "imgurl": "leoyang.jpg"},
    {"name": "Max Zhang", "imgurl": "maxzhang.jpg"},
    {"name": "Michael Hu", "imgurl": "michaelhu.jpg"},
    {"name": "Michael Ma", "imgurl": "michaelma.jpg"},
    {"name": "Michael Song", "imgurl": "michaelsong.jpg"},
    {"name": "Neil Weaver", "imgurl": "neilweaver.jpg"},
    {"name": "Oliver Ye", "imgurl": "oliverye.jpg"},
    {"name": "Oliver Zhang", "imgurl": "oliverzhang.jpg"},
    {"name": "Ray Zhou", "imgurl": "rayzhou.jpg"},
    {"name": "Royce Ren", "imgurl": "royceren.jpg"},
    {"name": "Sam Yang", "imgurl": "samyang.jpg"},
    {"name": "Samika Swamy", "imgurl": "samikaswamy.jpg"},
    {"name": "Samuel Shen", "imgurl": "samuelshen.jpg"},
    {"name": "Sean Yang", "imgurl": "seanyang.jpg"},
    {"name": "Spencer He", "imgurl": "spencerhe.jpg"},
    {"name": "Stefan Meier", "imgurl": "stefanmeier.jpg"},
    {"name": "Steven Long", "imgurl": "stevenlong.jpg"},
    {"name": "Tim Jing", "imgurl": "timjing.jpg"},
    {"name": "Tony Jiang", "imgurl": "tonyjiang.jpg"},
    {"name": "Tony Zhou", "imgurl": "tonyzhou.jpg"},
    {"name": "Victor Shen", "imgurl": "victorshen.jpg"},
    {"name": "Viola Zhao", "imgurl": "violazhao.jpg"},
    {"name": "Yaswanth Jampani", "imgurl": "yaswanthjampani.jpg"},
    {"name": "Zachary George", "imgurl": "zacharygeorge.jpg"},
    {"name": "Zachary Wang", "imgurl": "zacharywang.jpg"},
];
var Teachers2018 = [
    {"name": "Alex Lee", "imgurl": "alexlee.jpg"},
    {"name": "Alex Niu", "imgurl": "alexniu.jpg"},
    {"name": "Alex Yun", "imgurl": "alexyun.jpg"},
    {"name": "Alex Zheng", "imgurl": "alexzheng.jpg"},
    {"name": "Alvin Tian", "imgurl": "alvintian.jpg"},
    {"name": "Andrew Zhao", "imgurl": "andrewzhao.jpg"},
    {"name": "Andrew Zhou", "imgurl": "andrewzhou.jpg"},
    {"name": "Andy Li", "imgurl": "andyli.jpg"},
    {"name": "Andy Xu", "imgurl": "andyxu.jpg"},
    {"name": "Ansh Chaurasia", "imgurl": "anshchaurasia.jpg"},
    {"name": "Arthur Ji", "imgurl": "arthurji.jpg"},
    {"name": "Arthur Zhou", "imgurl": "arthurzhou.jpg"},
    {"name": "Ashok Sheridan", "imgurl": "ashoksheridan.jpg"},
    {"name": "Brandon Fu", "imgurl": "brandonfu.jpg"},
    {"name": "Chris Lee", "imgurl": "chrislee.jpg"},
    {"name": "Cindy Li", "imgurl": "cindyli.jpg"},
    {"name": "Cindy Xu", "imgurl": "cindyxu.jpg"},
    {"name": "Claire Cheng", "imgurl": "clairecheng.jpg"},
    {"name": "Darren Zhan", "imgurl": "darrenzhan.jpg"},
    {"name": "Emma Lu", "imgurl": "emmalu.jpg"},
    {"name": "Eric Ren", "imgurl": "ericren.jpg"},
    {"name": "Ethan Chen", "imgurl": "ethanchen.jpg"},
    {"name": "Henry Huang", "imgurl": "henryhuang.jpg"},
    {"name": "Henry Ying", "imgurl": "henryying.jpg"},
    {"name": "Jeffrey Tian", "imgurl": "jeffreytian.jpg"},
    {"name": "Joey He", "imgurl": "joeyhe.jpg"},
    {"name": "Joshua Si", "imgurl": "joshuasi.jpg"},
    {"name": "Julia Zhao", "imgurl": "juliazhao.jpg"},
    {"name": "Leo Yang", "imgurl": "leoyang.jpg"},
    {"name": "Mallika Parulekar", "imgurl": "mallikaparulekar.jpg"},
    {"name": "Martin Cooper", "imgurl": "martincooper.jpg"},
    {"name": "Max Zhang", "imgurl": "maxzhang.jpg"},
    {"name": "Michael Hu", "imgurl": "michaelhu.jpg"},
    {"name": "Michael Ma", "imgurl": "michaelma.jpg"},
    {"name": "Michael Zheng", "imgurl": "michaelzheng.jpg"},
    {"name": "Neil Weaver", "imgurl": "neilweaver.jpg"},
    {"name": "Oliver Ye", "imgurl": "oliverye.jpg"},
    {"name": "Ray Zhou", "imgurl": "rayzhou.jpg"},
    {"name": "Royce Ren", "imgurl": "royceren.jpg"},
    {"name": "Sam Yang", "imgurl": "samyang.jpg"},
    {"name": "Sean Yang", "imgurl": "seanyang.jpg"},
    {"name": "Shawn Huang", "imgurl": "shawnhuang.jpg"},
    {"name": "Shreya Kashyap", "imgurl": "shreyakashyap.jpg"},
    {"name": "Stefan Meier", "imgurl": "stefanmeier.jpg"},
    {"name": "Steven Long", "imgurl": "stevenlong.jpg"},
    {"name": "Tim Jing", "imgurl": "timjing.jpg"},
    {"name": "Tony Jiang", "imgurl": "tonyjiang.jpg"},
    {"name": "Tony Liao", "imgurl": "tonyliao.jpg"},
    {"name": "Tristan Cooper", "imgurl": "tristancooper.jpg"},
    {"name": "Viola Zhao", "imgurl": "violazhao.jpg"},
    {"name": "Zachary Wang", "imgurl": "zacharywang.jpg"},
];
var Teachers2017 = [
    {"name": "Alvin Tian", "imgurl": "alvintian.jpg"},
    {"name": "Andrew Zhao", "imgurl": "andrewzhao.jpg"},
    {"name": "Andrew Zhou", "imgurl": "andrewzhou.jpg"},
    {"name": "Andy Li", "imgurl": "andyli.jpg"},
    {"name": "Arthur Ji", "imgurl": "arthurji.jpg"},
    {"name": "Benjamin Owens", "imgurl": "benjaminowens.jpg"},
    {"name": "Brandon Fu", "imgurl": "brandonfu.jpg"},
    {"name": "Bryan Owens", "imgurl": "bryanowens.jpg"},
    {"name": "Cindy Li", "imgurl": "cindyli.jpg"},
    {"name": "Cindy Xu", "imgurl": "cindyxu.jpg"},
    {"name": "Claire Cheng", "imgurl": "clairecheng.jpg"},
    {"name": "Eric Yang", "imgurl": "ericyang.jpg"},
    {"name": "Frances Zhuang", "imgurl": "franceszhuang.jpg"},
    {"name": "George Wang", "imgurl": "georgewang.jpg"},
    {"name": "Gilbert Feng", "imgurl": "gilbertfeng.jpg"},
    {"name": "Henry Huang", "imgurl": "henryhuang.jpg"},
    {"name": "Jason Yang", "imgurl": "jasonyang.jpg"},
    {"name": "Jeffrey Tian", "imgurl": "jeffreytian.jpg"},
    {"name": "Joshua Si", "imgurl": "joshuasi.jpg"},
    {"name": "Julia Zhao", "imgurl": "juliazhao.jpg"},
    {"name": "Leo Yang", "imgurl": "leoyang.jpg"},
    {"name": "Matthew Wu", "imgurl": "matthewwu.jpg"},
    {"name": "Max Zhang", "imgurl": "maxzhang.jpg"},
    {"name": "Michael Ma", "imgurl": "michaelma.jpg"},
    {"name": "Oliver Ye", "imgurl": "oliverye.jpg"},
    {"name": "Paul Zhao", "imgurl": "paulzhao.jpg"},
    {"name": "Raymond Feng", "imgurl": "raymondfeng.jpg"},
    {"name": "Sam Yang", "imgurl": "samyang.jpg"},
    {"name": "Sean Yang", "imgurl": "seanyang.jpg"},
    {"name": "Shawn Huang", "imgurl": "shawnhuang.jpg"},
    {"name": "Stefan Meier", "imgurl": "stefanmeier.jpg"},
    {"name": "Stephanie Lee", "imgurl": "stephanielee.jpg"},
    {"name": "Steven Long", "imgurl": "stevenlong.jpg"},
    {"name": "Tim Jing", "imgurl": "timjing.jpg"},
    {"name": "Tony Jiang", "imgurl": "tonyjiang.jpg"},
    {"name": "Tony Liao", "imgurl": "tonyliao.jpg"},
    {"name": "Trinity Gao", "imgurl": "trinitygao.jpg"},
    {"name": "Viola Zhao", "imgurl": "violazhao.jpg"},
    {"name": "Winnie Zhao", "imgurl": "winniezhao.jpg"},
];
var Teachers2016 = [
    {"name": "Alvin Tian", "imgurl": "alvintian.jpg"},
    {"name": "Andrew Zhao", "imgurl": "andrewzhao.jpg"},
    {"name": "Andrew Zhou", "imgurl": "andrewzhou.jpg"},
    {"name": "Arthur Ji", "imgurl": "arthurji.jpg"},
    {"name": "Benjamin Owens", "imgurl": "benjaminowens.jpg"},
    {"name": "Brandon Fu", "imgurl": "brandonfu.jpg"},
    {"name": "Bryan Owens", "imgurl": "bryanowens.jpg"},
    {"name": "Jason Yang", "imgurl": "jasonyang.jpg"},
    {"name": "Jeffrey Tian", "imgurl": "jeffreytian.jpg"},
    {"name": "Oliver Ye", "imgurl": "oliverye.jpg"},
    {"name": "Samuel Yang", "imgurl": "samuelyang.jpg"},
    {"name": "Tony Jiang", "imgurl": "tonyjiang.jpg"},
];
var Teachers2015 = [
    {"name": "Bryan Owens", "imgurl": "bryanowens.jpg"},
];
for (var m=0; m<7; m++) {
    var container;
    var Teachers;
    if(m==0) {
        Teachers = Teachers2021;
        container = document.getElementById("2021")
    }else if(m==1) {
        Teachers = Teachers2020;
        container = document.getElementById("2020")
    }else if (m==2){
        Teachers = Teachers2019;
        container = document.getElementById("2019")
    }else if (m==3) {
        Teachers = Teachers2018;
        container = document.getElementById("2018")
    }else if (m==4) {
        Teachers = Teachers2017;
        container = document.getElementById("2017")
    }else if (m==5) {
        Teachers = Teachers2016;
        container = document.getElementById("2016")
    }else if (m==6) {
        Teachers = Teachers2015;
        container = document.getElementById("2015")
    }
    console.log(Teachers)
    console.log(container)
    for (var i = 0; i<Teachers.length; i++) {
        if(i%4 == 0) {
            var row = document.createElement('div')
            row.className += " row"
            row.setAttribute("data-aos", "fade-up")
            container.appendChild(row)
        }
        var column = document.createElement('div')
        column.className += " col-lg-3 teacher-div"
        column.innerHTML = Teachers[i].name
        var imgContainer = document.createElement('div')
        imgContainer.className += ' img-container'
        var link = "./images/ResizedTeamPhotos/" + Teachers[i].imgurl
        imgContainer.style.backgroundImage = 'url(' + link  + ')'
        column.appendChild(imgContainer)
        // var img = document.createElement('img')
        // img.className += ' teacher-img'
        // img.setAttribute('src', "./images/team/" + teachers[i].imgurl)
        // column.appendChild(img)
        container.lastChild.appendChild(column)

    }
}
