function Class2018(classname, datestr, locationstr, classNumber, spreadsheetURL) {
    this.classname      = classname;
    this.datestr        = datestr;
    this.locationstr    = locationstr;
    this.classNumber    = classNumber;
    this.spreadsheetURL = spreadsheetURL;
}
var classArray = [];
classArray.push(new Class2018("Intro to Web Design", "Sunday 5-6:30pm", "Omei Academy", 8, ""));
classArray.push(new Class2018("Intro to Java", "Sunday 5-6:30pm", "Omei Academy", 8, ""));
classArray.push(new Class2018("AMC 8", "Sunday 5-6:30pm", "Omei Academy", 10, ""));
classArray.push(new Class2018("Intro to Machine Learning", "Sunday 6:45-8:15pm", "Omei Academy", 9, ""));
classArray.push(new Class2018("Physics", "Sunday 6:45-8:15pm", "Omei Academy", 8, ""));
classArray.push(new Class2018("Intro to Java", "Saturday 5:15-6:45pm", "Omei Academy", 8, ""));
classArray.push(new Class2018("USACO Bronze", "Saturday 5:15-6:45pm", "Omei Academy", 8, ""));
classArray.push(new Class2018("Intermediate Java", "Saturday 5:15-6:45pm", "Omei Academy", 8, ""));
classArray.push(new Class2018("Public Speaking and Debate", "Saturday 7-8:30pm", "Omei Academy", 8, ""));
classArray.push(new Class2018("Biology", "Saturday 7-8:30pm", "Omei Academy", 8, ""));
classArray.push(new Class2018("MathCounts", "Saturday 10:30am-12pm", "Saratoga Fire Station", 8, ""));
classArray.push(new Class2018("Science Bowl", "Saturday 1-2:30pm", "Saratoga Fire Station", 6, ""));
classArray.push(new Class2018("Advanced Web Design", "Saturday 5:30-6:30pm", "Saratoga Fire Station", 6, ""));
classArray.push(new Class2018("Public Speaking", "Saturday 6:45-8pm", "Saratoga Fire Station", 8, ""));
classArray.push(new Class2018("Competitive Speech and Current Events", "Sunday 2:45-4:15pm", "Saratoga Fire Station", 8, ""));
classArray.push(new Class2018("World History", "Sunday 4:30-5:30", "Saratoga Fire Station", 8, ""));
classArray.push(new Class2018("AMC 8 Advanced", "Saturday 4-5:30pm", "Gunn High School", 7, ""));
classArray.push(new Class2018("Intro to Python", "Saturday 4-5:30pm", "Gunn High School", 8, ""));
classArray.push(new Class2018("Grammar and Vocab", "Friday 7-8:30pm", "Miller Middle School", 8, ""));
classArray.push(new Class2018("Bridge", "Friday 7-8:30pm", "Miller Middle School", 8, ""));
classArray.push(new Class2018("Public Speaking and Debate", "Friday 7-8:30pm", "Miller Middle School", 6, ""));
classArray.push(new Class2018("Public Speaking and Current Events", "Friday 7-8:30pm", "Miller Middle School", 8, ""));
classArray.push(new Class2018("Basketball", "Friday 5-7pm", "Dilworth Elementary School", 8, ""));
classArray.push(new Class2018("Tennis", "Sunday 3:30-5pm", "Saratoga Oaks Tennis Courts", 8, ""));