var teachers = [
    {"name": "Bryan Owens", "imgurl": "BryanOwens.jpg"},
    {"name": "Benjamin Owens", "imgurl": "BenjaminOwens.jpg"},
    {"name": "Aarav Garai", "imgurl": "AaravGarai.jpg"},
    {"name": "Aiden Ye", "imgurl": "AidenYe.jpg"},
    {"name": "Alan Yue", "imgurl": "AlanYue.jpg"},
    {"name": "Alex Lee", "imgurl": "AlexLee.jpg"},
    {"name": "Alex Niu", "imgurl":"AlexNiu.jpg"},
    {"name": "Alex Wang", "imgurl": "AlexWang.jpg"},
    {"name": "Alex Xu", "imgurl":"AlexXu.jpg"},
    {"name": "Alex Zhang", "imgurl":"AlexZhang.jpg"},
    {"name": "Alex Zheng", "imgurl":"AlexZheng.png"},
    {"name": "Alison Yang", "imgurl":"AlisonYang.jpg"},
    {"name": "Alvin Tian", "imgurl":"AlvinTian.jpg"},
    {"name": "Andrew Zhao", "imgurl":"AndrewZhao.jpg"},
    {"name": "Andrew Zhou", "imgurl":"AndrewZhou.jpg"},
    {"name": "Anthony Zhou", "imgurl": "AnthonyZhou.jpg"},
    {"name": "Andy Li", "imgurl":"AndyLi.jpg"},
    {"name": "Andy Xu", "imgurl":"AndyXu.jpg"},
    {"name": "Angela Li", "imgurl": "AngelaLi.jpg"},
    {"name": "Angelica Wang", "imgurl":"AngelicaWang.jpg"},
    {"name": "Angeline Hu", "imgurl":"AngelineHu.jpg"},
    {"name": "Anna Yang", "imgurl":"AnnaYang.jpg"},
    {"name": "Annli Zhu", "imgurl":"AnnliZhu.jpg"},
    {"name": "Anouk Yeh", "imgurl":"AnoukYeh.jpg"},
    {"name": "Anping Zhu", "imgurl":"AnpingZhu.jpg"},
    {"name": "Ansh Chaurasia", "imgurl":"AnshChaurasia.jpg"},
    {"name": "Archer Jin", "imgurl": "ArcherJin.jpg"},
    {"name": "Arthur Ji", "imgurl":"ArthurJi.jpg"},
    {"name": "Arthur Zhou", "imgurl":"ArthurZhou.jpg"},
    {"name": "Ashok Sheridan", "imgurl":"AshokSheridan.jpg"},
    {"name": "Austin Liu", "imgurl":"AustinLiu.jpg"},
    {"name": "Brandon Fu", "imgurl":"BrandonFu.jpg"},
    {"name": "Bryan Han", "imgurl": "BryanHan.jpg"},
    {"name": "Bryan Liu", "imgurl":"BryanLiu.jpg"},
    {"name": "Carter Bian", "imgurl":"CarterBian.jpg"},
    {"name": "Cayden Gu", "imgurl":"CaydenGu.jpg"},
    {"name": "Charles Li", "imgurl":"CharlesLi.jpg"},
    {"name": "Chloe Lee", "imgurl":"ChloeLee.jpg"},
    {"name": "Chris Lee", "imgurl":"ChrisLee.jpg"},
    {"name": "Cindy Li", "imgurl":"CindyLi.jpg"},
    {"name": "Cindy Xu", "imgurl":"CindyXu.jpg"},
    {"name": "Claire Cheng", "imgurl":"ClaireCheng.jpg"},
    {"name": "Crystal Zhu", "imgurl": "CrystalZhu.jpg"},
    {"name": "Cynthia Jia", "imgurl":"CynthiaJia.jpg"},
    {"name": "Darren Zhan", "imgurl":"DarrenZhan.jpg"},
    {"name": "Derrick Cai", "imgurl":"DerrickCai.jpg"},
    {"name": "Derek Li", "imgurl":"DerekLi.jpg"},
    {"name": "Edward Feng", "imgurl": "EdwardFeng.jpg"},
    {"name": "Elliot Seo", "imgurl": "ElliotSeo.jpg"},
    {"name": "Emma Lu", "imgurl":"EmmaLu.jpg"},
    {"name": "Emily Yang", "imgurl":"EmilyYang.jpg"},
    {"name": "Eric Ren", "imgurl":"EricRen.jpg"},
    {"name": "Eric Wang", "imgurl":"EricWang.jpg"},
    {"name": "Eric Yang", "imgurl":"EricYang.jpg"},
    {"name": "Ethan Chen", "imgurl":"EthanChen.jpg"},
    {"name": "Florence Wei", "imgurl": "FlorenceWei.jpg"},
    {"name": "Frances Zhuang", "imgurl": "FrancesZhuang.JPG"},
    {"name": "Grace Li", "imgurl": "GraceLi.jpg"},
    {"name": "Gabrielle He", "imgurl": "GabrielleHe.jpg"},
    {"name": "Henry Huang", "imgurl":"HenryHuang.jpg"},
    {"name": "Henry Ying", "imgurl":"henryying.jpg"},
    {"name": "Isaac Li", "imgurl":"IsaacLi.jpg"},
    {"name": "Isabella Shen", "imgurl": "IsabellaShen.jpg"},
    {"name": "Isabella Watson", "imgurl":"IsabellaWatson.jpg"},
    {"name": "Isaiah Sit", "imgurl":"IsaiahSit.jpg"},
    {"name": "Jason Kuo", "imgurl": "JasonKuo.jpg"},
    {"name": "Jason Yang", "imgurl":"JasonYang.jpg"},
    {"name": "Jasmine Yuan", "imgurl":"JasmineYuan.jpg"},
    {"name": "Jeffrey Tian", "imgurl":"JeffreyTian.jpg"},
    {"name": "Jerry Ying", "imgurl":"JerryYing.jpg"},
    {"name": "Joey He", "imgurl":"JoeyHe.jpg"},
    {"name": "Joshua Si", "imgurl":"JoshuaSi.jpg"},
    {"name": "Joshua Zhu", "imgurl":"JoshuaZhu.jpg"},
    {"name": "Julia Zhao", "imgurl":"JuliaZhao.jpg"},
    {"name": "Justin Gu", "imgurl":"JustinGu.jpg"},
    {"name": "Kaitlyn Wang", "imgurl":"KaitlynWang.jpg"},
    {"name": "Kevin Shi", "imgurl":"KevinShi.jpg"},
    {"name": "Kevin Wang", "imgurl":"KevinWang.jpg"},
    {"name": "Kurn Sundaram", "imgurl": "KurnSundaram.jpg"},
    {"name": "Kyleen Liao", "imgurl":"KyleenLiao.jpg"},
    {"name": "Leo Yang", "imgurl":"LeoYang.jpg"},
    {"name": "Lucas Lum", "imgurl":"LucasLum.jpg"},
    {"name": "Mallika Parulekar", "imgurl":"MallikaParulekar.jpg"},
    {"name": "Martin Cooper", "imgurl":"MartinCooper.jpg"},
    {"name": "Matthew Wu", "imgurl":"MatthewWu.jpg"},
    {"name": "Max Zhang", "imgurl":"MaxZhang.jpg"},
    {"name": "Michael Hu", "imgurl":"MichaelHu.jpg"},
    {"name": "Michael Ma", "imgurl":"MichaelMa.jpg"},
    {"name": "Michael Song", "imgurl":"MichaelSong.jpg"},
    {"name": "Michael Zheng", "imgurl":"MichaelZheng.jpg"},
    {"name": "Minh Do", "imgurl":"MinhDo.jpg"},
    {"name": "Neil Weaver", "imgurl":"NeilWeaver.jpg"},
    {"name": "Oliver Ye", "imgurl":"OliverYe.jpg"},
    {"name": "Oliver Zhang", "imgurl":"OliverZhang.jpg"},
    {"name": "Paul Zhao", "imgurl":"PaulZhao.jpg"},
    {"name": "Rachel Chan", "imgurl":"RachelChan.jpg"},
    {"name": "Ray Zhou", "imgurl":"RayZhou.jpg"},
    {"name": "Raymond Feng", "imgurl":"RaymondFeng.jpg"},
    {"name": "Royce Ren", "imgurl":"RoyceRen.jpg"},
    {"name": "Sam Yang", "imgurl":"SamYang.jpg"},
    {"name": "Samika Swamy", "imgurl":"SamikaSwamy.jpg"},
    {"name": "Samuel Ma", "imgurl": "SamuelMa.jpg"},
    {"name": "Samuel Yang", "imgurl":"SamuelYang.jpg"},
    {"name": "Sean Wu", "imgurl":"SeanWu.jpg"},
    {"name": "Sean Yang", "imgurl":"SeanYang.jpg"},
    {"name": "Seabert Mao", "imgurl":"SeabertMao.jpg"},
    {"name": "Shawn Huang", "imgurl":"ShawnHuang.jpg"},
    {"name": "Shreya Kashyap", "imgurl":"ShreyaKashyap.jpg"},
    {"name": "Shreyas Rana", "imgurl":"ShreyasRana.jpg"},
    {"name": "Skyler Mao", "imgurl":"SkylerMao.jpg"},
    {"name": "Stefan Meier", "imgurl":"StefanMeier.jpg"},
    {"name": "Stephanie Lee", "imgurl":"StephanieLee.jpg"},
    {"name": "Steven Long", "imgurl":"StevenLong.jpg"},
    {"name": "Sudithi Manthati", "imgurl":"SudithiManthati.jpg"},
    {"name": "Taimin Lio", "imgurl":"TaiminLio.jpg"},
    {"name": "Thomas Wu", "imgurl":"ThomasWu.jpg"},
    {"name": "Tim Jing", "imgurl":"TimJing.jpg"},
    {"name": "Timothy Leung", "imgurl":"TimothyLeung.jpg"},
    {"name": "Tony Jiang", "imgurl":"TonyJiang.jpg"},
    {"name": "Tony Zhou", "imgurl":"TonyZhou.jpg"},
    {"name": "Trinity Gao", "imgurl":"TrinityGao.jpg"},
    {"name": "Tristan Cooper", "imgurl":"TristanCooper.jpg"},
    {"name": "Victor Shen", "imgurl":"VictorShen.jpg"},
    {"name": "Viola Zhao", "imgurl":"ViolaZhao.jpg"},
    {"name": "Winnie Zhao", "imgurl":"WinnieZhao.jpg"},
    {"name": "Yash Ranjith", "imgurl":"YashRanjith.jpg"},
    {"name": "Yashnil Mohanty", "imgurl": "YashnilMohanty.jpg"},
    {"name": "Zachary Wang", "imgurl":"ZacharyWang.jpg"}
]
